title = "No More Headaches"
baseURL = "https://as4mo3.github.io/NoMoreHeadaches/"
languageCode = "en-us"
theme = "airspace-hugo"
publishDir = "docs"

[menu]

  [[menu.header]]
    weight = 2
    name = "Work"
    url = "/work"
#  [[menu.header]]
#    weight = 3
#    name = "Other"
#    url = "/blog"

  [[menu.footer]]
    weight = 1
    name = "About us"
    url = "#"
  [[menu.footer]]
    weight = 2
    name = "Contact us"
    url = "#"
  [[menu.footer]]
    weight = 3
    name = "How it works"
    url = "#"
  [[menu.footer]]
    weight = 4
    name = "Blog"
    url = "#"
  [[menu.footer]]
    weight = 5
    name = "Terms"
    url = "#"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "Revolutionizing headache treatment without costly physician visits"
    subtitle = "When patients enter their headache information into our web application, our machine learning algorithms analyzes whether they should go to a physician for tests."

  [params.wrapper]
    enable = true
    title = "Misson Statement"
    paragraph = "Transforming the way that clinicians diagnose headaches by empowering patients to share their headache symptoms in real time. Then, by analyzing headache patterns, and following the clinical outcomes associated with each pattern, our algorithm will learn to recognize if a patient’s headache pattern indicates that they are high or low risk. Our program will improve patient outcomes, reduce radiation exposure, and decrease medical costs."

#  [params.blog]
#    enable = true
#    title = "Get The Latest On What We're doing"
#    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "We believe in great ideas"
    content = "Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
    [params.feature.button]
      caption = "View Works"
      url = "#"

  [params.call]
    enable = true
    title = "We design delightful digital experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
